name: "Set Issue Label"
on:
  pull_request:
    types: [opened]

jobs:
  please-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thank you for your pull request! Please add a label to your PR to help categorize the changelog, and adjust the title of your PR for consumption in release notes.'
            })
